### ISSUE TITLE
(Mobile) Player Frigate laser does not render properly.

### ISSUE THREAD

**Issue by GRKTheGreat** [jhrushbe/MOARdustry#13] opened 2023-08-04 10:19 UTC
it points inwards and is the same size as the player... No idea if it even works as a weapon because of my previous bug(https://github.com/jhrushbe/MOARdustry/issues/12).

**Comment by jhrushbe** [comment] 2023-08-04 20:56
I can confirm that it is not a mobile only issue, happens on PC too. The laser is the right size and shape and does function properly, but it is pointed in the wrong direction for some reason even though the weapon's code should function in the same manner as Vela's.

**Comment by jhrushbe** [comment] 2023-08-04 21:16
Now fixed. Error seemed to be due to a new animation for the ContinuousLaserBulletType which starts the laser behind the firing point by the length of the weapon then moves it forward by the length value. Increasing the length value to 45 made the laser no longer cover the frigate's sprite.

**Closed as completed by jhrushbe** 2023-08-04 21:16 UTC

**Comment by GRKTheGreat** [comment] 2023-08-05 05:33
nice
